baseURL = "http://localhost:1313/"
title = "我的随笔博客"
theme = "PaperMod"
defaultContentLanguage = "zh"
hasCJKLanguage = true
paginate = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 3

[params]
author = "笔者"
description = "个人随笔记录"
homeInfoParams = {Title = "欢迎来到我的随笔博客", Content = "日常文字记录"}
ShowPostNavLinks = true
ShowCodeCopyButtons = true
assets.disableFingerprinting = true